networks:
  web:
    name: web
  intercom:
    name: intercom

volumes:
  order_pg_vol:

services:
  traefik:
    image: "traefik:v3.5.2"
    container_name: traefik
    # todo add traefik config
    # todo only expose network web
    command:
      - "--api.dashboard=true" # enable dashboard
      - "--api.insecure=true" # enable insecure access to dashboard
      - "--providers.docker=true" # enable docker as provider
      - "--providers.docker.exposedbydefault=false" # disable all containers by default
      - "--providers.docker.network=web" # set docker network that will be used by traefik to web
      - "--entrypoints.web.address=:80" # define entrypoint web on port 80
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web


  orderservice:
    container_name: orderservice
    build: .
    command: [ "/app/ordersystem" ]
    depends_on:
      - order-postgres
    restart: unless-stopped
    # todo add traefik labels
    labels:
      - "traefik.enable=true" # enable traefik for this service
      - "traefik.http.routers.orderservice.rule=Host(`orders.localhost`)" # define routing rule
      - "traefik.http.routers.orderservice.entrypoints=web" # define entrypoint
      - "traefik.http.services.orderservice.loadbalancer.server.port=3000" # define internal port
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_TCP_PORT=5432
      - DB_HOST=order-postgres
    networks:
      - intercom
      - web

  sws:
    image: joseluisq/static-web-server:latest
    container_name: sws
    # todo add frontend folder as volume
    volumes:
      - ./frontend:/public
    # todo setup environment variables to expose port 80 and serve the frontend folder
    environment:
      - SERVER_ROOT=/public
      - SERVER_PORT=80
    restart: unless-stopped
    # todo add traefik labels
    labels:
      - "traefik.enable=true" # enable traefik for this service
      - "traefik.http.routers.sws.rule=Host(`localhost`)" # define routing rule
      - "traefik.http.routers.sws.entrypoints=web" # define entrypoint
      - "traefik.http.services.sws.loadbalancer.server.port=80" # define internal port
    networks:
      - web

  order-postgres:
    image: postgres:latest
    restart: always
    networks:
      - intercom
    volumes:
      - order_pg_vol:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_TCP_PORT=5432